# Generated by Django 3.1 on 2021-11-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Sr', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=50)),
                ('uname', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
