# Generated by Django 3.1 on 2021-11-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(default='', max_length=200),
        ),
    ]
