# Generated by Django 3.1 on 2021-11-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0003_question_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Ques',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
